### ISSUE TITLE
Save persistence plots in file instead of showing them

### ISSUE THREAD

**Issue by ptrus** [adolenc/topotext#11]

**Comment by RokIvansek** [comment]
-make a directory figures where you will save the graphs
-pay attention to names of graphs (they should be descriptive) (use labels from main.py)
-dont show graphs at all (just save them)

**Comment by RokIvansek** [comment]
Done. While plotting I saw births and deaths are floats this makes graphs look a little strange. Shouldn't those be integers???

**Comment by adolenc** [comment]
Right now we are not making the filtration as it was described in the instructions (using R and splitting the interval [0, R] to 10 equal-sized parts), so I think the deaths/births are actually just epsilons at which simplices get added to complex (correct me if my understanding is incorrect). If you want to change that, uncomment [src/persistence_diagrams.py#L46](https://github.com/adolenc/topotext/blob/master/src/persistence_diagrams.py#L46).
