### ISSUE TITLE
Make generic preprocessor

### ISSUE THREAD

**Issue by adolenc** [adolenc/topotext#2]
Preprocessor should accept:
- [x] a path to directory of files (which it loads and sends to pre-preprocessor);
- [x] a pre-preprocessor, which takes as input a text and produces a list of words;
- [x] a list of functions which generate features;
- [x] optional parameter which makes it also include tf/idf features; 

and combines all of the features into matrices X and y.

**Comment by RokIvansek** [comment]
Running Prepreprocesor class gives me an error:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 7: ordinal not in range(128)

**Comment by RokIvansek** [comment]
Fixed using decode('utf-8') in utils.
